Add request progress listener
DoveConviene/dc-volley pull request #2
Opened 2017-07-12 21:12 UTC by alexpopa95

Image downloads have now track of progress

2017-07-14 09:53 UTC, andreaboi83 commented on src/main/java/com/android/volley/Response.java
> +        public void onProgress(long transferredBytes, long totalSize, long millisSpent);
@alexpopa95 non sarebbe male se il progress avesse un metodo aggiuntivo che notifichi la sola percentuale di avanzamento, quindi un numero da 0 a 100.

Questo perchè uno potrebbe non essere interessato a conoscere ogni singolo parametro e quindi a eseguire da se i calcoli. Se io voglio pilotare una progress bar, ad esempio, non ho necessità di sapere ne i byte ne nulla, ma solo a che punto è il download.

2017-07-14 10:00 UTC, andreaboi83 requested changes

2017-07-14 10:00 UTC, andreaboi83 commented on src/main/java/com/android/volley/toolbox/BasicNetwork.java
> +    private ProgressListener mProgressListener;
@alexpopa95 qui ti chiederei di effettuare alcune modifiche.

Non è necessario che il progress listener sia definito come variabile. E' meglio che sia utilizzato localmente.

Fai l'overload del metodo `entityToBytes`, o, se la cosa non comporta problemi, modifica la signature in modo che prenda in ingresso il progress listener.

Dato che il progress listener è implementato a livello di request, il progress può essere notificato alla sola request e non mischiamo troppo le cose.

2017-07-14 10:00 UTC, andreaboi83 commented on src/main/java/com/android/volley/toolbox/ImageRequest.java
> +public class ImageRequest extends Request<Bitmap> implements Response.ProgressListener {
@alexpopa95 e se il progress listener fosse implementato da tutte le request?? Come lo vedi?

2017-07-21 09:46 UTC, alexpopa95 commented
@andreaboi83 Il DefaultRetryListener ora è sempre a livello di ImageLoader ma definito SOLO alla sua creazione (nel costruttore)

Codice riformattato dopo le modifiche

Aggiunta la soluzione definitiva (con javadoc a sufficienza e commenti) sul calcolo del progresso del download

2017-09-21 14:27 UTC, Bxttx approved these changes

2017-09-21 14:28 UTC, merged